name: Build and deploy PHP app to Azure Web App - bloodbank-webapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'src/composer.json'  # <-- src içine bakar

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        working-directory: src   # <-- önemli!
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Upload artifact from src directory only
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'bloodbank-webapp'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C00E2C55DC954C008A4305D7A0693818 }}
